package vu.tp.mybatis.model;

public class Game {

    private Integer leagueId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.ID
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.AWAYTEAMPOINTS
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    private Integer awayteampoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.HOMETEAMPOINTS
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    private Integer hometeampoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.TEAM_AWAY
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    private Integer teamAway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.TEAM_HOME
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    private Integer teamHome;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.ID
     *
     * @return the value of PUBLIC.GAME.ID
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.ID
     *
     * @param id the value for PUBLIC.GAME.ID
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.AWAYTEAMPOINTS
     *
     * @return the value of PUBLIC.GAME.AWAYTEAMPOINTS
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public Integer getAwayteampoints() {
        return awayteampoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.AWAYTEAMPOINTS
     *
     * @param awayteampoints the value for PUBLIC.GAME.AWAYTEAMPOINTS
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public void setAwayteampoints(Integer awayteampoints) {
        this.awayteampoints = awayteampoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.HOMETEAMPOINTS
     *
     * @return the value of PUBLIC.GAME.HOMETEAMPOINTS
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public Integer getHometeampoints() {
        return hometeampoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.HOMETEAMPOINTS
     *
     * @param hometeampoints the value for PUBLIC.GAME.HOMETEAMPOINTS
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public void setHometeampoints(Integer hometeampoints) {
        this.hometeampoints = hometeampoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.TEAM_AWAY
     *
     * @return the value of PUBLIC.GAME.TEAM_AWAY
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public Integer getTeamAway() {
        return teamAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.TEAM_AWAY
     *
     * @param teamAway the value for PUBLIC.GAME.TEAM_AWAY
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public void setTeamAway(Integer teamAway) {
        this.teamAway = teamAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME.TEAM_HOME
     *
     * @return the value of PUBLIC.GAME.TEAM_HOME
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public Integer getTeamHome() {
        return teamHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME.TEAM_HOME
     *
     * @param teamHome the value for PUBLIC.GAME.TEAM_HOME
     *
     * @mbg.generated Tue Apr 21 19:43:43 EEST 2020
     */
    public void setTeamHome(Integer teamHome) {
        this.teamHome = teamHome;
    }

    public Integer getLeagueId(){ return this.leagueId; }

    public void setLeagueId(Integer leagueId) { this.leagueId = leagueId; }
}