package vu.tp.mybatis.model;

public class League {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEAGUE.ID
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LEAGUE.NAME
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEAGUE.ID
     *
     * @return the value of PUBLIC.LEAGUE.ID
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEAGUE.ID
     *
     * @param id the value for PUBLIC.LEAGUE.ID
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LEAGUE.NAME
     *
     * @return the value of PUBLIC.LEAGUE.NAME
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LEAGUE.NAME
     *
     * @param name the value for PUBLIC.LEAGUE.NAME
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}