package vu.tp.mybatis.model;

public class Playergamestats {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERGAMESTATS.ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERGAMESTATS.ASSISTS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    private Integer assists;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERGAMESTATS.POINTS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    private Integer points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERGAMESTATS.REBOUNDS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    private Integer rebounds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERGAMESTATS.GAME_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    private Integer gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERGAMESTATS.PLAYER_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    private Integer playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERGAMESTATS.TEAM_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    private Integer teamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERGAMESTATS.ID
     *
     * @return the value of PUBLIC.PLAYERGAMESTATS.ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERGAMESTATS.ID
     *
     * @param id the value for PUBLIC.PLAYERGAMESTATS.ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERGAMESTATS.ASSISTS
     *
     * @return the value of PUBLIC.PLAYERGAMESTATS.ASSISTS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public Integer getAssists() {
        return assists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERGAMESTATS.ASSISTS
     *
     * @param assists the value for PUBLIC.PLAYERGAMESTATS.ASSISTS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public void setAssists(Integer assists) {
        this.assists = assists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERGAMESTATS.POINTS
     *
     * @return the value of PUBLIC.PLAYERGAMESTATS.POINTS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERGAMESTATS.POINTS
     *
     * @param points the value for PUBLIC.PLAYERGAMESTATS.POINTS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERGAMESTATS.REBOUNDS
     *
     * @return the value of PUBLIC.PLAYERGAMESTATS.REBOUNDS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public Integer getRebounds() {
        return rebounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERGAMESTATS.REBOUNDS
     *
     * @param rebounds the value for PUBLIC.PLAYERGAMESTATS.REBOUNDS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public void setRebounds(Integer rebounds) {
        this.rebounds = rebounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERGAMESTATS.GAME_ID
     *
     * @return the value of PUBLIC.PLAYERGAMESTATS.GAME_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERGAMESTATS.GAME_ID
     *
     * @param gameId the value for PUBLIC.PLAYERGAMESTATS.GAME_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERGAMESTATS.PLAYER_ID
     *
     * @return the value of PUBLIC.PLAYERGAMESTATS.PLAYER_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERGAMESTATS.PLAYER_ID
     *
     * @param playerId the value for PUBLIC.PLAYERGAMESTATS.PLAYER_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERGAMESTATS.TEAM_ID
     *
     * @return the value of PUBLIC.PLAYERGAMESTATS.TEAM_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERGAMESTATS.TEAM_ID
     *
     * @param teamId the value for PUBLIC.PLAYERGAMESTATS.TEAM_ID
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }
}