package vu.tp.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.tp.mybatis.model.Playergamestats;

@Mapper
public interface PlayergamestatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERGAMESTATS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERGAMESTATS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    int insert(Playergamestats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERGAMESTATS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    Playergamestats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERGAMESTATS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    List<Playergamestats> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERGAMESTATS
     *
     * @mbg.generated Sun Apr 26 01:38:05 EEST 2020
     */
    int updateByPrimaryKey(Playergamestats record);
}