package vu.tp.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.tp.mybatis.model.Team;

@Mapper
public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    Team selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    List<Team> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Wed Apr 15 22:05:38 EEST 2020
     */
    int updateByPrimaryKey(Team record);

    List<Team> selectTeamsByLeagueId(Integer leagueId);
}